// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1ScheduleReminderResponse v1 schedule reminder response
//
// swagger:model v1ScheduleReminderResponse
type V1ScheduleReminderResponse struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this v1 schedule reminder response
func (m *V1ScheduleReminderResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 schedule reminder response based on context it is used
func (m *V1ScheduleReminderResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1ScheduleReminderResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1ScheduleReminderResponse) UnmarshalBinary(b []byte) error {
	var res V1ScheduleReminderResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
